Update requirements.txt
Exception: The official Pinecone python package has been renamed from 

`pinecone-client` to `pinecone`. Please remove `pinecone-client` from your 

project dependencies and add `pinecone` instead. See the README at 

https://github.com/pinecone-io/pinecone-python-client for more information on 

using the python SDK.